select * from product ;
insert into area (id, describetion, image) values (null, 'main imagex', 'main_area.jpg') ;

insert into sub_area (id, area_id , positiony, positionx, describetion, image , rental_arrears ) values (null, 1 , 0.20, 0.35 , 'zone  A' , 'ZONE_A.jpg' , '1,000,000' ) ;
insert into sub_area (id, area_id , positiony, positionx, describetion, image , rental_arrears ) values (null, 1 , 0.25, 0.50 , 'zone  B' , 'ZONE_B.jpg' , '0' ) ;
insert into sub_area (id, area_id , positiony, positionx, describetion, image , rental_arrears ) values (null, 1 , 0.30, 0.80 , 'zone  C' , 'ZONE_C.jpg' , '0' ) ;
insert into sub_area (id, area_id , positiony, positionx, describetion, image , rental_arrears ) values (null, 1 , 0.40, 0.30 , 'zone  D' , 'ZONE_D.jpg' , '12,000,000' ) ;
insert into sub_area (id, area_id , positiony, positionx, describetion, image , rental_arrears ) values (null, 1 , 0.40, 0.40 , 'zone  E' , 'ZONE_E.jpg' , '2,000,000' ) ;
insert into sub_area (id, area_id , positiony, positionx, describetion, image , rental_arrears ) values (null, 1 , 0.45, 0.70 , 'zone  F' , 'ZONE_F.jpg' , '3,000,000	' ) ;
insert into sub_area (id, area_id , positiony, positionx, describetion, image , rental_arrears ) values (null, 1 , 0.50, 0.50 , 'zone  G' , 'ZONE_G.jpg' , '12,000,000' ) ;
insert into sub_area (id, area_id , positiony, positionx, describetion, image , rental_arrears ) values (null, 1 , 0.50, 0.83 , 'zone  H' , 'ZONE_H.jpg' , '0' ) ;
insert into sub_area (id, area_id , positiony, positionx, describetion, image , rental_arrears ) values (null, 1 , 0.80, 0.45 , 'zone  I' , 'ZONE_I.jpg' , '0' ) ;
insert into sub_area (id, area_id , positiony, positionx, describetion, image , rental_arrears ) values (null, 1 , 0.80, 0.60 , 'zone  J' , 'ZONE_J.jpg' , '0' ) ;

insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 1 , 0.45, 0.70 , 'zone  F' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'3,000,000	' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 1 , 0.50, 0.50 , 'zone  G' , 'home_v3.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'12,000,000' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 1 , 0.50, 0.83 , 'zone  H' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 1 , 0.80, 0.45 , 'zone  I' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 1 , 0.80, 0.60 , 'zone  J' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;

insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 2 , 0.20, 0.35 , 'zone  A' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 2 , 0.25, 0.50 , 'zone  B' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 2 , 0.30, 0.80 , 'zone  C' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 2 , 0.80, 0.45 , 'zone  I' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 2 , 0.80, 0.60 , 'zone  J' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;

insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 3 , 0.25, 0.50 , 'zone  B' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 3 , 0.30, 0.80 , 'zone  C' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 3 , 0.50, 0.83 , 'zone  H' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 3 , 0.80, 0.45 , 'zone  I' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 3 , 0.80, 0.60 , 'zone  J' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;

insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 4 , 0.20, 0.35 , 'zone  A' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'1,000,000' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 4 , 0.25, 0.50 , 'zone  B' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 4 , 0.30, 0.80 , 'zone  C' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 4 , 0.40, 0.30 , 'zone  D' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'12,000,000' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 4 , 0.40, 0.40 , 'zone  E' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'2,000,000' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 4 , 0.45, 0.70 , 'zone  F' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'3,000,000	' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 4 , 0.50, 0.50 , 'zone  G' , 'home_v3.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'12,000,000' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 4 , 0.50, 0.83 , 'zone  H' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 4 , 0.80, 0.45 , 'zone  I' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 4 , 0.80, 0.60 , 'zone  J' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;

insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 5 , 0.20, 0.35 , 'zone  A' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'1,000,000' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 5 , 0.25, 0.50 , 'zone  B' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 5 , 0.30, 0.80 , 'zone  C' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 5 , 0.40, 0.30 , 'zone  D' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'12,000,000' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 5 , 0.40, 0.40 , 'zone  E' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'2,000,000' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 5 , 0.45, 0.70 , 'zone  F' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'3,000,000	' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 5 , 0.50, 0.50 , 'zone  G' , 'home_v3.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'12,000,000' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 5 , 0.50, 0.83 , 'zone  H' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 5 , 0.80, 0.45 , 'zone  I' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 5 , 0.80, 0.60 , 'zone  J' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;

insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 6 , 0.20, 0.35 , 'zone  A' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'1,000,000' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 6 , 0.25, 0.50 , 'zone  B' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 6 , 0.30, 0.80 , 'zone  C' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 6 , 0.40, 0.30 , 'zone  D' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'12,000,000' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 6 , 0.40, 0.40 , 'zone  E' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'2,000,000' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 6 , 0.45, 0.70 , 'zone  F' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'3,000,000	' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 6 , 0.50, 0.50 , 'zone  G' , 'home_v3.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'12,000,000' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 6 , 0.50, 0.83 , 'zone  H' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 6 , 0.80, 0.45 , 'zone  I' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 6 , 0.80, 0.60 , 'zone  J' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;

insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 7 , 0.20, 0.35 , 'zone  A' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'1,000,000' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 7 , 0.25, 0.50 , 'zone  B' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 7 , 0.30, 0.80 , 'zone  C' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 7 , 0.40, 0.30 , 'zone  D' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'12,000,000' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 7 , 0.40, 0.40 , 'zone  E' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'2,000,000' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 7 , 0.45, 0.70 , 'zone  F' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'3,000,000	' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 7 , 0.50, 0.50 , 'zone  G' , 'home_v3.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'12,000,000' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 7 , 0.50, 0.83 , 'zone  H' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 7 , 0.80, 0.45 , 'zone  I' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 7 , 0.80, 0.60 , 'zone  J' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;

insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 8 , 0.20, 0.35 , 'zone  A' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 8 , 0.25, 0.50 , 'zone  B' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 8 , 0.30, 0.80 , 'zone  C' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 8 , 0.40, 0.30 , 'zone  D' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 8 , 0.40, 0.40 , 'zone  E' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 8 , 0.45, 0.70 , 'zone  F' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 8 , 0.50, 0.50 , 'zone  G' , 'home_v3.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 8 , 0.50, 0.83 , 'zone  H' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 8 , 0.80, 0.45 , 'zone  I' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 8 , 0.80, 0.60 , 'zone  J' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;

insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 9 , 0.20, 0.35 , 'zone  A' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 9 , 0.25, 0.50 , 'zone  B' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 9 , 0.30, 0.80 , 'zone  C' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 9 , 0.40, 0.30 , 'zone  D' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 9 , 0.40, 0.40 , 'zone  E' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 9 , 0.45, 0.70 , 'zone  F' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 9 , 0.50, 0.50 , 'zone  G' , 'home_v3.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;

insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 10 , 0.20, 0.35 , 'zone  A' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 10 , 0.25, 0.50 , 'zone  B' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 10 , 0.30, 0.80 , 'zone  C' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 10 , 0.40, 0.30 , 'zone  D' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 10 , 0.40, 0.40 , 'zone  E' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;
insert into shop (id, sub_area_id , positiony, positionx, describetion, image , due_date , number_Lock , status, shop_name , product_type , size_space, monthly_Rent, rental_arrears ) values (null, 10 , 0.45, 0.70 , 'zone  F' , 'home_v2.jpg' , CURRENT_TIMESTAMP , '1234','1' , ' icream' , 'icream' , '24 Square meters.' , '10,000 baht/month' ,'0' ) ;
